config/routes.rb
Rails.application.routes.draw do
  
    get 'homepages/index'
    devise_for :admin
    devise_scope :admin do
        authenticated :admin do
            root to: 'pages#dashboard', as: :authenticated_root
        end
        unauthenticated do
            root :to => 'admin/sessions#new', as: :unauthenticated_root
        end
    end
    #Dash board for all Models
    get '/admin' => 'pages#dashboard'
    #Restaurants 
    namespace :admin do
        resources :restaurants do
            resources :dishes
            resources :locations
        end 
    end 
    namespace :admin do
        resources :dishes do
            resources :ratings
        end  
    end  
    
    namespace :admin do
        #Restarants
        resources :restaurants
        #Dish categories
        resources :categories
        #Dishes
        resources :dishes
        #Locations
        resources :locations
        #Ratings
        resources :ratings
    end 
    #home page
    get '/search' => 'homepages#index', :as => 'home' 
    get '/dish/search' => 'homepages#search', :as => 'search_dish' 
    get '/dish/map' => 'homepages#map'
    get '/dishes/:id' => 'homepages#show', :as => 'dishes_show' 
end

app/models/dish.rb
class Dish < ApplicationRecord
  has_many :ratings, :dependent => :destroy
  has_many :pictures, as: :imageable
  has_and_belongs_to_many :restaurants
  belongs_to :category, optional: true	
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  validates_presence_of :name, message: '*Enter Dish name'
  validates_presence_of :price, message: '*Enter Dish Price'
  validates :category_id, presence: true
  scope :search, ->(searchdish) {where("name LIKE ?", "#{searchdish}%")}
  scope :sortby_price, ->(price) {order(price)}
  scope :sortby_ratings, ->(name) {joins(:ratings).group('dishes.id').having("name LIKE ?", "#{name}%").order('avg(ratings.number) desc')}
  scope :sortby_rating, ->(rating) {joins(:ratings).group('dishes.id').having('avg(ratings.number) > ?', rating).order('avg(ratings.number) desc')}
  scope :sortby_dietary, ->(category) {where(category_id: category)}

end

app/controllers/admin/dishes_controller.rb
class Admin::DishesController < ApplicationController
    def index   
        @dishes = Dish.paginate(:page => params[:page], :per_page => 10)   
    end   
 
    def show   
        @dish = Dish.find(params[:id])   
    end   
    def new   
        @dish = Dish.new
        @dish.pictures.build  
    end   
   
    def create
        @restaurant = Restaurant.find(params[:restaurant_id])
        @dish =  @restaurant.dishes.create(dish_params)
        if @dish.save   
            flash[:notice] = 'dish added!'   
            redirect_to admin_restaurants_path    
        else   
            flash[:error] = 'Failed to create dish!'   
            render :new   
        end   
    end   
   
    def edit   
        @dish = Dish.find(params[:id])
    end   

    def update   
        @dish = Dish.find(params[:id])   
        if @dish.update_attributes(dish_params)   
            flash[:notice] = 'Dish updated!'   
            redirect_to admin_restaurants_path  
        else   
            flash[:error] = 'Failed to edit Dish!'   
            render :edit   
        end   
    end   
   
    def destroy   
        @dish = Dish.find(params[:id])   
        if @dish.delete   
            flash[:notice] = 'Dish deleted!'   
            redirect_to admin_dishes_path   
        else   
            flash[:error] = 'Failed to delete this Dish!'   
            render :destroy   
        end
    end 

    private
    def dish_params   
        params.require(:dish).permit(:name, :price, :category_id, :restaurant_id, pictures_attributes: [:id, :name])   
    end 
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController

  def index   
    @dishes = Dish.all   
  end   
   
  def show   
    @dish = Dish.find(params[:id])   
  end   
  
  def new   
    @dish = Dish.new
    @dish.pictures.build  
  end   
   
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @dish =  @restaurant.dishes.create(dish_params)
    if @dish.save   
      flash[:notice] = 'dish added!'   
      redirect_to dishes_path    
    else   
      flash[:error] = 'Failed to edit dish!'   
      render :new   
    end   
  end   
   
  def edit   
    @dish = Dish.find(params[:id]) 
  end   

  def update   
    @dish = Dish.find(params[:id])   
    if @dish.update_attributes(dish_params)   
      flash[:notice] = 'Dish updated!'   
      redirect_to dishes_path   
    else   
      flash[:error] = 'Failed to edit Dish!'   
      render :edit   
    end   
  end   
   
  def destroy   
    @dish = Dish.find(params[:id])   
    if @dish.delete   
      flash[:notice] = 'Dish deleted!'   
      redirect_to dishes_path   
    else   
      flash[:error] = 'Failed to delete this Dish!'   
      render :destroy   
    end
  end 

  def dish_params   
    params.require(:dish).permit(:name, :price, :category_id, :restaurant_id, pictures_attributes: [:name])   
  end 
end

app/helpers/dishes_helper.rb
module DishesHelper
end

app/views/dishes/edit.html.erb
<div class="container center">   
  <%= form_for @dish, url: {action: :update} do |f| %>   
    <div>   
      <h3>Edit Dish</h3>   
    </div>   
    <div>   
      <p>   
        <%= "<div>#{@restaurant.errors.full_messages.first}</div>".html_safe if @dish.errors.any? %>   
      <div class="form-group">   
          <label>Dish Name</label>   
          <%= f.text_field :name, :class => "form-control", :placeholder => 'Enter Dish Name' %>   
      </div>
      <div class="form-group">   
          <label>Price</label>   
          <%= f.text_field :price, :class => "form-control", :placeholder => 'Enter price' %>   
      </div>
      <div class="form-group">
      	<label>Category</label>   
      	<%= f.select( :category_id, options_from_collection_for_select(Category.all, "id", "name"), {}, {:class => 'form-control'}) %>
      </div>	
      <div class="form-group"> 
        <%= f.fields_for :pictures do |p|%>
          <label>Upload Image</label> <br/>
          <%= p.file_field :name%>
        <%end%>
      </div>  	
    <div>
    <div class="form-group row">
      <div class="text-left"> 
        <%= link_to 'Back', dishes_path,	 :class => "btn btn-warning" %>   
      </div>
      <div class="text-right">  
        <%= f.submit 'Update', :class => "btn btn-info" %>   
      </div>
    </div>   
  <% end %>   
</div>  

app/views/dishes/index.html.erb
<div class="container">   
  <h3>DISH LIST</h3>   
    <div>   
      <%= link_to 'Back', restaurants_path,  :class => 'btn btn-primary' %>   
    </div>   
    <br>   
  <table border="2" class="table table-striped">   
    <thead>   
    <tr>   
      <th>Id</th>   
      <th>Name</th>   
      <th>Image</th>   
      <th>Price</th>   
      <th>Rating</th>   
      <th>Actions</th>   
    </tr>   
    </thead>   
    <tbody>   
      <% @dishes.each do |d| %>   
        <tr>   
          <td><%= d.id %></td>   
          <td><%= d.name %></td> 
          <td style="width: 100px;">
            <% d.pictures.each do|p|%>
              <%= image_tag(p.name_url, :class => 'image') %> 
            <% end %> 
          </td>  
          <td><%= d.price %></td>   
          <td><%= link_to 'Add Rating', new_dish_rating_path(d),  :class => 'btn btn-warning' %></td>   
          <td>   
            <%= link_to 'Edit', edit_dish_path(d), :class => 'btn btn-info' %>   
            <%= link_to 'Delete', dish_path(d), method: :delete, :class => 'btn btn-danger' %>   
          </td>   
        </tr>   
      <% end %>   
    </tbody>   
  </table>   
</div>

app/views/dishes/new.html.erb
<div class="container center">   
  <%= form_for @dish, url: {action: :create} do |f| %>   
      <div>   
        <h3>Add Dish</h3>   
      </div>
      <div>   
        <p>   
          <%= "<div>#{@dish.errors.full_messages.first}</div>".html_safe if @dish.errors.any? %>   
        <div class="form-group">   
            <label>Dish Name</label>   
            <%= f.text_field :name, :class => "form-control", :placeholder => 'Enter Dish Name' %>   
        </div>
        <div class="form-group">   
            <label>Price</label>   
            <%= f.text_field :price, :class => "form-control", :placeholder => 'Enter price' %>   
        </div>
        <div class="form-group">
        	<label>Category</label>   
        	<%= f.select( :category_id, options_from_collection_for_select(Category.all, "id", "name"), {}, {:class => 'form-control'}) %>
        </div>
        <div class="form-group"> 
          <%= f.fields_for :pictures do |p|%>
            <label>Upload Image</label> <br/>
            <%= p.file_field :name%>
          <%end%>
        </div>	
      <div>
      <div class="form-group row">
        <div class="text-left"> 
          <%= link_to 'Back', dishes_path,	 :class => "btn btn-warning" %>   
        </div>
        <div class="text-right">  
          <%= f.submit 'Create Dish', :class => "btn btn-info" %>   
        </div>
      </div>   
  <% end %>   
</div>  