config/routes.rb
Rails.application.routes.draw do
  
    get 'homepages/index'
    devise_for :admin
    devise_scope :admin do
        authenticated :admin do
            root to: 'pages#dashboard', as: :authenticated_root
        end
        unauthenticated do
            root :to => 'admin/sessions#new', as: :unauthenticated_root
        end
    end
    #Dash board for all Models
    get '/admin' => 'pages#dashboard'
    #Restaurants 
    namespace :admin do
        resources :restaurants do
            resources :dishes
            resources :locations
        end 
    end 
    namespace :admin do
        resources :dishes do
            resources :ratings
        end  
    end  
    
    namespace :admin do
        #Restarants
        resources :restaurants
        #Dish categories
        resources :categories
        #Dishes
        resources :dishes
        #Locations
        resources :locations
        #Ratings
        resources :ratings
    end 
    #home page
    get '/search' => 'homepages#index', :as => 'home' 
    get '/dish/search' => 'homepages#search', :as => 'search_dish' 
    get '/dish/map' => 'homepages#map'
    get '/dishes/:id' => 'homepages#show', :as => 'dishes_show' 
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :pictures, as: :imageable, dependent: :destroy
  has_and_belongs_to_many :dishes, dependent: :destroy
  has_and_belongs_to_many :locations, dependent: :destroy
  accepts_nested_attributes_for :pictures
  validates_presence_of :pictures
  validates_presence_of :name, message: '*Enter Restaurant name'
  validates :name, :uniqueness => { :case_sensitive => false}
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < ApplicationController
  
    def index   
        @restaurants = Restaurant.paginate(:page => params[:page], :per_page => 10)   
    end   
   
    def show   
        @restaurant = Restaurant.find(params[:id])
    end   

    def new   
        @restaurant = Restaurant.new 
        @restaurant.pictures.build  
    end   
   
    def create   
        @restaurant = Restaurant.new(restaurant_params)   
        if @restaurant.save   
            flash[:notice] = 'restaurant added!'   
            redirect_to admin_restaurants_path   
        else   
            flash[:error] = 'Failed to create restaurant!'   
            render :new   
        end   
    end   
   
    def edit   
        @restaurant = Restaurant.find(params[:id])
    end   
    def update   
        @restaurant = Restaurant.find(params[:id])   
        if @restaurant.update_attributes(restaurant_params)   
            flash[:notice] = 'Restaurant updated!'   
            redirect_to admin_restaurants_path   
        else   
            flash[:error] = 'Failed to edit Restaurant!'   
            render :edit   
        end   
    end   
    def destroy   
        @restaurant = Restaurant.find(params[:id])
        if @restaurant.delete   
            flash[:notice] = 'Restaurant deleted!'   
            redirect_to admin_restaurants_path   
        else   
            flash[:error] = 'Failed to delete this Restaurant!'   
            render :destroy   
        end   
    end   

    private
    def restaurant_params   
        params.require(:restaurant).permit(:name, pictures_attributes: [:id, :name])   
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  
  def index   
    @restaurants = Restaurant.paginate(:page => params[:page], :per_page => 10)   
  end   
   
  def show   
    @restaurant = Restaurant.find(params[:id])
  end   
  
  def new   
    @restaurant = Restaurant.new 
    @restaurant.pictures.build  
  end   
   
  def create   
    @restaurant = Restaurant.new(restaurant_params)   
    if @restaurant.save   
      flash[:notice] = 'restaurant added!'   
      redirect_to restaurants_path   
    else   
      flash[:error] = 'Failed to edit restaurant!'   
      render :new   
    end   
  end   
   
  def edit   
    @restaurant = Restaurant.find(params[:id])
  end   

  def update   
    @restaurant = Restaurant.find(params[:id])   
    if @restaurant.update_attributes(restaurant_params)   
      flash[:notice] = 'Restaurant updated!'   
      redirect_to restaurants_path   
    else   
      flash[:error] = 'Failed to edit Restaurant!'   
      render :edit   
    end   
  end   
   
  def destroy   
    @restaurant = Restaurant.find(params[:id])
    if @restaurant.delete   
      flash[:notice] = 'Restaurant deleted!'   
      redirect_to restaurants_path   
    else   
      flash[:error] = 'Failed to delete this Restaurant!'   
      render :destroy   
    end   
  end   

  def restaurant_params   
    params.require(:restaurant).permit(:name, pictures_attributes: [:name])   
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/index.html.erb
<div class="container">   
  <h3>RESTAURANT LIST</h3>   
    <div>   
      <%= link_to 'Add Restaurant', new_restaurant_path, :class => "btn btn-success" %>   
    </div>   
    <br>   
  <table border="2" class="table table-striped">   
    <thead>   
    <tr>   
      <th>Id</th>   
      <th>Name</th>   
      <th>Image</th>   
      <th>Dish</th>   
      <th>Add Dish</th>   
      <th>Add Location</th>   
      <th>Actions</th>   
    </tr>   
    </thead>   
    <tbody>   
	    <% @restaurants.each do |r| %>   
	      <tr>   
	        <td><%= r.id %></td>   
	        <td><%= r.name %></td>
          <td style="width: 100px;">
            <% r.pictures.each do|p|%>
              <%= image_tag p.name_url, :class => 'image', "data-toggle"=>"modal", "data-target" => "#img-#{r.id}" %>
            <div class="modal fade" id="img-<%= r.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
              <div class="modal-dialog" role="document" style="margin-top: 90px;">
                <div class="modal-content modal-center">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button> 
                  </div>
                  <div class="modal-body">
                    <%= image_tag p.name_url %>
                  </div>
                </div>
              </div>
            </div>
           
            <% end %> 
          </td>
          <td>
            <%= r.dishes.pluck(:name).join(',')%>
          </td>
          <td><%= link_to 'Add Dish', new_restaurant_dish_path(r), :class => "btn btn-info" %></td>   
          <td><%= link_to 'Add Location', new_restaurant_location_path(r), :class => "btn btn-warning" %></td>   
	        <td>   
            <%= link_to 'Show', restaurant_path(r), :class => "btn btn-success" %>
	          <%= link_to 'Edit', edit_restaurant_path(r), :class => "btn btn-primary" %>
	          <%= link_to 'Delete', restaurant_path(r), method: :delete, data: {confirm: "Are you sure?"} , :class => "btn btn-danger"%>   
	        </td>   
	      </tr>   
	    <% end %>   
    </tbody>   
  </table>
  <div class="page"><%= will_paginate @restaurants %></div>   
</div>   